language: java

node_js: "4.4.7"

install: 
  - npm install
  - npm install -g gulp-cli
  - mvn -N io.takari:maven:wrapper

script: "./mvnw spring-boot:run & ; bootPid=$! sleep 30s ;  gulp itest ;  kill $bootPid"
