language: java

node_js: "4.4.7"

install: 
  - npm install
  - npm install -g gulp-cli

script: "npm test"

script:
  - ./mvnw spring-boot:run && bootPid=$!
  - sleep 30s
  - gulp itest
  - kill $bootPid
