dist: trusty
jdk:
  - openjdk8

language: java

addons:
  firefox: "47.0"

node_js: "7"

before_install:
  - mkdir lib
  - wget "https://ncloud.neoware.cz/index.php/s/XjkDTkeiOxFVamz/download?path=%2F&files=spring-data-elasticsearch-3.0.0.BUILD-SNAPSHOT.jar" -O lib/spring-data-elasticsearch-3.0.0.BUILD-SNAPSHOT.jar

install:
  - nvm install v7.10.0
  - node -v
  - npm -v
  - npm install
  - npm install -g gulp-cli
  - mvn -N io.takari:maven:wrapper
  - ./node_modules/protractor/bin/webdriver-manager update --versions.chrome=2.31 --versions.standalone=3.5.3 --versions.gecko=v0.18.0

script: 
  - ./mvnw compile
  - ./mvnw test
  - ./mvnw spring-boot:run -Drun.profiles=integration &
  - sleep 30s
  - gulp itest
#  If there isn't running mvnw killall returns non-zero return code
  - killall mvnw
