dist: trusty
jdk:
  - openjdk8

language: java

node_js: "4.4.7"

before_install:
  - mkdir lib
  - wget "https://ncloud.neoware.cz/index.php/s/XjkDTkeiOxFVamz/download?path=%2F&files=spring-data-elasticsearch-3.0.0.BUILD-SNAPSHOT.jar" -O lib/spring-data-elasticsearch-3.0.0.BUILD-SNAPSHOT.jar

install:
  - nvm install v4.4.7
  - node -v
  - npm -v
  - npm install
  - npm install -g gulp-cli
  - mvn -N io.takari:maven:wrapper

script: 
  - ./mvnw compile
  - ./mvnw spring-boot:run &
  - sleep 30s
  - gulp itest
  - killall mvnw
