language: java

node_js: "4.4.7"

install:
  - nvm install v4.4.7
  - node -v
  - npm -v
  - npm install
  - npm install -g gulp-cli
  - mvn -N io.takari:maven:wrapper

script: 
  - ./mvnw spring-boot:run &
  - sleep 30s
  - gulp itest
  - killall mvnw
