management:
  context-path: /management
  health:
    mail:
      enabled: false
spring:
  application:
    name: mcsr
  profiles:
    active: null
  jackson:
    serialization.write_dates_as_timestamps: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
  messages:
    basename: i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
security:
  basic:
    enabled: false
cxf:
  path: /services
  jaxws:
    component-scan: true
    classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics,com.frequentis.maritime.mcsr.soap
jhipster:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
  cors:
    allowed-origins: '*'
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: '*'
    exposed-headers: null
    allow-credentials: true
    max-age: 1800
  mail:
    from: mcsr@localhost
  swagger:
    title: Maritime Cloud Service Registry API
    description: Maritime Cloud Service Registry, developed under the Horizon 2020 Project EfficienSea2, cofunded by the European Union.
    version: 1.0
    termsOfServiceUrl: null
    contactName: Frequentis AG
    contactUrl: http://www.frequentis.com
    contactEmail: josef.jahn@frequentis.com
    license: AGPLv3
    licenseUrl: https:/www.gnu.org/licenses/agpl-3.0.en.html
  ribbon:
    displayOnActiveProfiles: dev